version: "3.9"

services:
  api:
    build: ./api
    restart: unless-stopped
    ports:
      - 3132:3132
    volumes:
      - type: bind
        source: ./api
        target: /api
      - /app/node_modules # POG to prevent container's node_modules be overridden from host;
    command: sh -c "npm run prisma-init && npm run dev"
    networks:
      - the-confession-network

  web:
    build: ./web
    ports:
        - 5173:5173
    networks:
    - the-confession-network
    volumes:
      - type: bind
        source: ./web
        target: /web
      - /app/node_modules # POG to prevent container's node_modules be overridden from host;
    command: sh -c "npm run dev"

networks:
  the-confession-network: