export enum TagsEnum {
  NSFW = 'NSFW',
  GOOD_NEWS = 'GOOD_NEWS',
  BAD_NEWS = 'BAD_NEWS',
  RELATIONSHIP = 'RELATIONSHIP',
  DAY_TO_DAY = 'DAY_TO_DAY',
  DEPRESSION = 'DEPRESSION',
  OFF_MY_CHEST = 'OFF_MY_CHEST',
  OFF_MY_CHEST_WITHOUT_COMMENTS = 'OFF_MY_CHEST_WITHOUT_COMMENTS',
}